package com.duowan.ebguide.dao;

import com.duowan.ebguide.model.SnatchProduct;
import com.duowan.ebguide.model.SnatchProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SnatchProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int countByExample(SnatchProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int deleteByExample(SnatchProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int insert(SnatchProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int insertSelective(SnatchProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    List<SnatchProduct> selectByExample(SnatchProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    SnatchProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SnatchProduct record, @Param("example") SnatchProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SnatchProduct record, @Param("example") SnatchProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SnatchProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snatch_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SnatchProduct record);
    
    /**
     * insert record if productUrl exist then update record 
     *
     */
    int replaceByProductUrl(SnatchProduct record);
    
    List<SnatchProduct> selectByLimit(@Param("offset") Integer offset, @Param("limit") Integer limit, @Param("website") String website);
}