package com.duowan.ebguide.model;

import java.util.Date;

public class SnatchProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.website
     *
     * @mbggenerated
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productBrand
     *
     * @mbggenerated
     */
    private String productBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productName
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productCategory
     *
     * @mbggenerated
     */
    private String productCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productUrl
     *
     * @mbggenerated
     */
    private String productUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productGender
     *
     * @mbggenerated
     */
    private String productGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productImages
     *
     * @mbggenerated
     */
    private String productImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productSoldCount
     *
     * @mbggenerated
     */
    private Integer productSoldCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.productRemainCount
     *
     * @mbggenerated
     */
    private Integer productRemainCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.discountPrice
     *
     * @mbggenerated
     */
    private Float discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.originalPrice
     *
     * @mbggenerated
     */
    private Float originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.discountRate
     *
     * @mbggenerated
     */
    private Float discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.startTime
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.endTme
     *
     * @mbggenerated
     */
    private Date endTme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_product.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.id
     *
     * @return the value of snatch_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.id
     *
     * @param id the value for snatch_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.website
     *
     * @return the value of snatch_product.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.website
     *
     * @param website the value for snatch_product.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productBrand
     *
     * @return the value of snatch_product.productBrand
     *
     * @mbggenerated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productBrand
     *
     * @param productBrand the value for snatch_product.productBrand
     *
     * @mbggenerated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand == null ? null : productBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productName
     *
     * @return the value of snatch_product.productName
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productName
     *
     * @param productName the value for snatch_product.productName
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productCategory
     *
     * @return the value of snatch_product.productCategory
     *
     * @mbggenerated
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productCategory
     *
     * @param productCategory the value for snatch_product.productCategory
     *
     * @mbggenerated
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory == null ? null : productCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productUrl
     *
     * @return the value of snatch_product.productUrl
     *
     * @mbggenerated
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productUrl
     *
     * @param productUrl the value for snatch_product.productUrl
     *
     * @mbggenerated
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl == null ? null : productUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productGender
     *
     * @return the value of snatch_product.productGender
     *
     * @mbggenerated
     */
    public String getProductGender() {
        return productGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productGender
     *
     * @param productGender the value for snatch_product.productGender
     *
     * @mbggenerated
     */
    public void setProductGender(String productGender) {
        this.productGender = productGender == null ? null : productGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productImages
     *
     * @return the value of snatch_product.productImages
     *
     * @mbggenerated
     */
    public String getProductImages() {
        return productImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productImages
     *
     * @param productImages the value for snatch_product.productImages
     *
     * @mbggenerated
     */
    public void setProductImages(String productImages) {
        this.productImages = productImages == null ? null : productImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productSoldCount
     *
     * @return the value of snatch_product.productSoldCount
     *
     * @mbggenerated
     */
    public Integer getProductSoldCount() {
        return productSoldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productSoldCount
     *
     * @param productSoldCount the value for snatch_product.productSoldCount
     *
     * @mbggenerated
     */
    public void setProductSoldCount(Integer productSoldCount) {
        this.productSoldCount = productSoldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.productRemainCount
     *
     * @return the value of snatch_product.productRemainCount
     *
     * @mbggenerated
     */
    public Integer getProductRemainCount() {
        return productRemainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.productRemainCount
     *
     * @param productRemainCount the value for snatch_product.productRemainCount
     *
     * @mbggenerated
     */
    public void setProductRemainCount(Integer productRemainCount) {
        this.productRemainCount = productRemainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.discountPrice
     *
     * @return the value of snatch_product.discountPrice
     *
     * @mbggenerated
     */
    public Float getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.discountPrice
     *
     * @param discountPrice the value for snatch_product.discountPrice
     *
     * @mbggenerated
     */
    public void setDiscountPrice(Float discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.originalPrice
     *
     * @return the value of snatch_product.originalPrice
     *
     * @mbggenerated
     */
    public Float getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.originalPrice
     *
     * @param originalPrice the value for snatch_product.originalPrice
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Float originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.discountRate
     *
     * @return the value of snatch_product.discountRate
     *
     * @mbggenerated
     */
    public Float getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.discountRate
     *
     * @param discountRate the value for snatch_product.discountRate
     *
     * @mbggenerated
     */
    public void setDiscountRate(Float discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.startTime
     *
     * @return the value of snatch_product.startTime
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.startTime
     *
     * @param startTime the value for snatch_product.startTime
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.endTme
     *
     * @return the value of snatch_product.endTme
     *
     * @mbggenerated
     */
    public Date getEndTme() {
        return endTme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.endTme
     *
     * @param endTme the value for snatch_product.endTme
     *
     * @mbggenerated
     */
    public void setEndTme(Date endTme) {
        this.endTme = endTme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_product.updateTime
     *
     * @return the value of snatch_product.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_product.updateTime
     *
     * @param updateTime the value for snatch_product.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}